### ISSUE TITLE
.try isn't defined

### ISSUE THREAD

**Issue by digitalfx** [sxross/MotionModel#133]
https://github.com/sxross/MotionModel/blob/08e0c6b7cc0bf92ed160fd8f290f67a901fb5ad9/motion/model/model.rb#L729
The above line of code is calling `owner.try(:id)` however `try` hasn't been defined anywhere (nor is motion-support depended upon). I was going to make a PR, but after mulling over 3 different ways of fixing this, I thought it probably best to let you choose the best plan of attack :rocket:

**Comment by sxross** [comment]
Can I have a failing spec? I have an implementation but would like a clean spec to test against. MotionSupport seems like a lot to pull in just to have `try`. Although, I did move a bunch of stuff over there in the earlier phases of MotionModel development.

**Comment by digitalfx** [comment]
Awesome, thanks 👍
