### ISSUE TITLE
New objects are receiving duplicate IDs when app is quit and relaunched

### ISSUE THREAD

**Issue by digitalfx** [sxross/MotionModel#135]
This only seems to occur after exiting and reloading, but I'm experiencing an id related issue with deleted records. Spec coming. Best way to illustrate is with this example:
`rake`
```ruby
    t1 = Task.create(name: "One")
    t2 = Task.create(name: "Two")
    t3 = Task.create(name: "Three")
    t2.destroy

    Task.each { |t| puts "Task id:#{t.id} name: #{t.name}" }
    # Task id:1 name: One
    # Task id:3 name: Three

    Task.serialize_to_file('tasks.dat')
    exit
```
`rake`
```ruby
    Task.deserialize_from_file('tasks.dat')
    Task.each { |t| puts "Task id:#{t.id} name: #{t.name}" }
    # Task id:1 name: One
    # Task id:3 name: Three

    t4 = Task.create(name: "Four")
    Task.each { |t| puts "Task id:#{t.id} name: #{t.name}" }
    # Task id:1 name: One
    # Task id:3 name: Three
    # Task id:3 name: Four
```
Note the duplicate ID on the last line.

**Comment by sxross** [comment]
Um...eeeek?

**Comment by digitalfx** [comment]
Yes, I thought that when I finally realised what was happening.

**Comment by digitalfx** [comment]
Ok, I think this may be the problem:
In `array_model_persistence.rb` the objects are deserialized on line 71, which in turn calls `initWithCoder` on 155. The very first line of this is `self.init` which moves us to `model.rb` and line 418 which is `def initialize`.

At this point `before_initialize(options)` is called, which eventually calls `increment_next_id` in `array_model_adapter.rb`. However, the options hash currently contains an id of nil, so the `_next_id` variable is simply counting up by 1.

Once the object has been initialized, it is only then that it's id field is being assigned back in `array_model_persistence.rb` after the `self.init` call.

**Comment by digitalfx** [comment]
This actually means that if 10 items were deserialized from file, which started with ids around 50, the next item would gain id 11, then 12 etc etc!
