### ISSUE TITLE
has_one relationship not working

### ISSUE THREAD

**Issue by holgersindbaek** [sxross/MotionModel#141]
I'm having some issues with the following models.

    class Listing
      include MotionModel::Model
      include MotionModel::ArrayModelAdapter

      # Colums
      columns :headline

      # Relationships
      has_one :user, dependent: :destroy
    end

    class User
      include MotionModel::Model
      include MotionModel::ArrayModelAdapter

      columns :first_name

      belongs_to :listing
    end

If I do the following:

    listing = Listing.create(headline: "Some headline")
    listing.user.create(first_name: "Some name")
    listing.user
    listing.user.first_name

I get the following error:
    
    (main)> listing.user
=> #<MotionModel::ArrayFinderQuery:0x11fb47850 @field_name=:listing_id @collection=[User#1:0x11f9943e0] @related_object=Listing#61:0x11fd00840 @klass=User>
    (main)> listing.user.first_name
2016-02-03 15:16:12.938 Slang[55648:459275] undefined method `first_name' for #<MotionModel::ArrayFinderQuery:0x11f774240 ...> (NoMethodError)
=> #<NoMethodError: undefined method `first_name' for #<MotionModel::ArrayFinderQuery:0x11f774240 ...>>

What is going on here? Why is the user not returned when I do "listing.user"?

**Comment by holgersindbaek** [comment]
@sxross No guess on what this might be about?!

**Comment by sxross** [comment]
Sorry I'm out for a week. Can would write a failing spec?

**Comment by holgersindbaek** [comment]
I'm not sure whether it's failing or whether it's supposed to be that way. Are you supposed to get back an 'ArrayFinderQuery' no matter what relationship you're calling? I can understand it with a 'has_many' relationship, but I think it's a bit weird with a 'has_one' relationship.

You don't have anything on the top of your head you think it might be? Read through the whole documentation an I'm eager to get going with MotionModel.

**Comment by sxross** [comment]
I think it's an implementation detail. What happens if you do some query.first? Does that give you the object you expect?

Regards,

Steve Ross

**Comment by holgersindbaek** [comment]
If I do 'listing.user.first', then I get the user and everything works as expected. Issue I have with that, is that in a 'has_one' relationship, there is only 1 user and therefore it's weird to me that you have to get the first user, as if it's an array.

It seems to me that the 'has_one' relationship is acting exactly like the 'has_many' relationship.

**Comment by sxross** [comment]
Right. So it's an implementation detail. How does Rails handle this?

Regards,

Steve Ross

**Comment by holgersindbaek** [comment]
If it's a 'has_one' relationship, Rails returns the object because there's only 1 object on a has_one relationship. In this case Rails would return the user. So in Rails, I would be able to do something like 'listing.user.first_name'.

in a 'has_many' relationship, Rails would return an array.

I've looked a bit around in the source code, but haven't been able to figure out how to return the object itself. Any hints on how to do this?

**Comment by sxross** [comment]
Perfect. Raise an issue. I am literally on a ship in the ocean so I can't do anything just now but soon.

Regards,

Steve Ross

**Comment by holgersindbaek** [comment]
Ok... can I just leave this issue here as the reference?!

Enjoy the ocean.

**Comment by sxross** [comment]
This is an interesting issue. Having looked at the code, I see that the reason the store is returned as a response to a `has_one` access is because the `has_one` and `has_many` code share common logic to handle getting and setting attributes. Why an `ArrayFinderQuery` would know how to do an assignment, your object won't. More concretely:

```ruby
a_person.profile.name = "Sam"
```

calls a setter for `name` on the store associated with `Profile`. See why this might be an issue to dereference it and return the `first` only?

**Comment by holgersindbaek** [comment]
I don't fully get you. Are you saying that how it works now is how it should work?

**Comment by sxross** [comment]
I'm saying how it works now is how it was designed. That can be changed but it's not a one-line.

**Comment by holgersindbaek** [comment]
Ok. I've tried to wrap my head around it, but I can't really figure it out. Is it something you would like to have a stab at? Wouldn't you agree it is a weird design as it is now?

**Comment by sxross** [comment]
I agree it's counter-intuitive. I think I know the change but need to figure out how to avoid breaking other peoples' working code. Full disclosure : I don't use has_one and actually didn't implement the feature.

**Comment by holgersindbaek** [comment]
Ok. Do you think it's going to take some time? Any timeline on it?

**Comment by sxross** [comment]
It's predicated on my other responsibilities so I can't predict. I'm sorry to be so vague. I just haven't settled on an implementation. If you want an idea of what I'm looking at, check model.rb line 710. I need that code to understand the context in which it's being called.

**Comment by holgersindbaek** [comment]
Ok... looking forward to it happening. Could be really nice to implement something like MotionModel.

**Comment by sxross** [comment]
@holgersindbaek: Can you look at this spec and see whether you think this would handle your use-case? I'm digging into this and want to make sure I've captured the `has_one` usage properly:

```ruby
class User
  include MotionModel::Model
  include MotionModel::ArrayModelAdapter

  columns :name => :string
  config_options do
    {has_one_behavior: :as_object}
  end

  has_one :profile
end

class Profile
  include MotionModel::Model
  include MotionModel::ArrayModelAdapter

  columns :email => :string

  belongs_to :user
end

describe 'has_one behaviors' do
  before {User.destroy_all; Profile.destroy_all}

  it 'returns an object when has_one relations are used' do
    u = User.create(name: 'Sam')
    p = Profile.create(email: 'ss@gmail.com')
    u.profile = p
    u.save
    User.first.profile.should.is_a?(Profile)
    User.first.profile.email.should == 'ss@gmail.com'
  end
end

```

**Comment by holgersindbaek** [comment]
That looks perfect.

**Comment by sxross** [comment]
Now to make it come true :)

**Comment by holgersindbaek** [comment]
Haha... looking forward to it.

**Comment by sxross** [comment]
@aceofspades -- you implemented this `has_one` relation (https://github.com/sxross/MotionModel/blame/master/motion/model/model.rb#L701) but it returns an ArrayFinderQuery. I don't know whether you remember why, but there is a fairly complex path to fulfill both getter and setter methods. If you follow this thread, @holgersindbaek expects (correctly, I believe) that `has_one` attributes may be used as object rather than being dereferenced using `first`. I'm wondering whether you had a rationale for this implementation and how we might make it more like the Rails behavior of returning the single object instance of the related attribute.

**Comment by aceofspades** [comment]
@sxross I'm thinking `_has_many_has_one_relation` should probably return a relation as it does, and then `get_has_one_attr` should dereference it with `first`.

**Comment by sxross** [comment]
Yes. That's exactly what I thought. One line of code and I'm done. But if you dereference with `first`, it breaks `set_has_one_attr` because the first thing `set_has_one_attr` is a `get_has_one_attr` and of course it's expecting a relation. I can poke around with changing `set_has_one_attr` to call `_has_many_has_one_relation` instead of `get_has_one_attr`. Do you think that would work?

Also, do you think it would be harmful to inject a `first` method of the instance so code that used to dereference won't break?

Thanks!

**Comment by aceofspades** [comment]
That sounds right, it almost seems like that's what I would have meant to do!

**Comment by holgersindbaek** [comment]
So the solution was simple? Has anything been pushed yet?!

-- 

All the best

Holger Sindbaek · UI/UX  Designer & Web/iOS Programmer  ·   HolgerSindbaek.com




On Fri, Feb 19, 2016 at 3:27 PM -0800, "Doug Puchalski" <notifications@github.com> wrote:












That sounds right, it almost seems like that's what I would have meant to do!

**Comment by sxross** [comment]
Nothing yet. Tests are still failing.

**Comment by sxross** [comment]
@aceofspades: I wonder if I understand how `has_one` is even supposed to work. I created a fresh branch, `has_one_as_object` and a spec `spec/has_one_as_object_spec.rb`. The spec fails on attribute assign (`attr=`). Note that I have made zero changes to the MotionModel code. Can you have a peek at this spec and tell me whether I have made an incorrect assumption about the original as-implemented expected behavior?

Thanks!

**Comment by aceofspades** [comment]
I doesn't look like you've saved the user after setting the profile, but that doesn't sound like your issue. I honestly don't recall after so long, but the intention would certainly be to behave like ActiveRecord.

**Comment by sxross** [comment]
For some reason I can't think of right now, I implemented the ability to use any Ruby type as a column. This has the side-effect of making this code possible:

```ruby
class Profile
  include MotionModel::Model
  include MotionModel::ArrayModelAdapter

  columns :email => :string


end

class User
  include MotionModel::Model
  include MotionModel::ArrayModelAdapter

  columns :name => :string,
          :profile => Profile

end
```

If direct embedding is what you are looking for in `has_one`, it's already there. If you were looking for inverse relation lookup, this won't work.

Comments?

**Comment by holgersindbaek** [comment]
I'm looking for inverse relation lookup. I want to be able to do both:

    listing = Listing.create(headline: "Some headline")
    listing.user.create(first_name: "Some name")
    listing.user # Find a listings user
    listing.user.listing # Find listing that belongs to user

Does that make sense?

**Comment by sxross** [comment]
Making progress. This was completely broken before, as far as I can tell.

**Comment by holgersindbaek** [comment]
Hehe ok... looking forward to seeing what you come up with :-).

**Comment by holgersindbaek** [comment]
@sxross How's it going?

**Comment by sxross** [comment]
The branch I'm working on actually implements has_one as it was originally designed. It's the first step. I'm getting to this as I can, but feel free to pitch in if you want to spread things up.

**Comment by holgersindbaek** [comment]
Have you pushed the branch so I can see?!

-- 

All the best

Holger Sindbaek · UI/UX  Designer & Web/iOS Programmer  ·   HolgerSindbaek.com




On Fri, Feb 26, 2016 at 9:54 PM -0800, "s.ross" <notifications@github.com> wrote:












The branch I'm working on actually implements has_one as it was originally designed. It's the first step. I'm getting to this as I can, but feel free to pitch in if you want to spread things up.

**Comment by sxross** [comment]
The branch is has_one_as_object. The specs should pass. The one to look at is has_one_as_object. What's there now is what caused you to raise this issue in the first place. 

What needs to happen is that create and create! need to exist on instances. They just forward to self.class.create or self.class.create!

Once that's done, get_has_one_attr can dereference the collection returning an instance, thus addressing this issue.

**Comment by holgersindbaek** [comment]
@sxross Never fully got your explanation of what needs to happen. Have you had a chance to look a bit more into it?

**Comment by sxross** [comment]
What `has_one` describes is a kind of embedding but not quite. So, the object that appears to be embedded is really a member of another collection. That means the member of the embeddable object -- the container needs to have a proxy to implement the right behavior so there is always a member available. That way `my_instance.profile != nil`.

**Comment by holgersindbaek** [comment]
I've had a bit of time to look into the `has_one` issue and this is how I see it solved: https://github.com/sxross/MotionModel/pull/142. 

I'm not sure if we misunderstood each other a bit. From what I can see from the specs in your branch, they don't describe the `has_one` functionality as it's supposed to work.

Looking forward to reading your comments on the fix.
