### ISSUE TITLE
Getting "Cache size 0" warnings

### ISSUE THREAD

**Issue by holgersindbaek** [sxross/MotionModel#146]
I've started to get these warnings in in my terminal and I'm quite sure I've started to get them after I started using MotionModel. I can't find any place in the MotionModel code that would output such a warning, but I simply don't know what else it could be:

```
May 11 18:16:43 Holger-Sindbaeks-iPhone Slang[1563] <Warning>: Cache size 0
```

Are you familiar with this warning? Am I right, that it's related to MotionModel?

**Comment by sxross** [comment]
This doesn't ring any bells. There is no string in MotionModel that warns about cache size. Have you pinged motion support?

**Comment by holgersindbaek** [comment]
No... you think it might be generally RubyMotion related?

**Comment by sxross** [comment]
It's hard to say, but the string does not exist in MotionModel as far as I can see and if it doesn't exist in your app, that leaves only 2 other places: Frameworks and RubyMotion. Right?

**Comment by holgersindbaek** [comment]
Can't argue with that. Thanks for the clarification!
